name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Yarn Installation
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: Yarn Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command
      - name: Install Surge
        run: npm install -g surge
        uses: UsmanAsif193/Surge-Action@v1.03
      - name: Deploying on Surge
        run: surge ./build bootcampreact2020_nabeelaltaf.surge.sh --token ${{secrets.SURGE_TOKEN}}
